# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d052a7df6bc469e569844d28a15a7c5"
application_url = "https://fictional-bassoon-pvpw5pq7ggwfqx6-4040.app.github.dev"
embedded = true
name = "team-info"
handle = "team-info-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fictional-bassoon-pvpw5pq7ggwfqx6-4040.app.github.dev/auth/callback",
  "https://fictional-bassoon-pvpw5pq7ggwfqx6-4040.app.github.dev/auth/shopify/callback",
  "https://fictional-bassoon-pvpw5pq7ggwfqx6-4040.app.github.dev/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "yaldaashop.myshopify.com"
automatically_update_urls_on_dev = true
